Description: >
  @David Hany
  creating Policy cloudFormation Statement
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-managedpolicy.html
Resources:
  Policy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: Policy for newbies
      ManagedPolicyName: newbies-S3-Policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:Get*
              - s3:List*
            Resource: '*'

          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:DeleteObject
            Resource: 'arn:aws:s3:::newbies-devs/*'
  
  Group:
    Type: AWS::IAM::Group
    Properties: 
      GroupName: newbies-S3-Group
      ManagedPolicyArns: 
        - Ref: Policy
      